# Generated by Django 5.2.1 on 2025-06-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('meaning', models.TextField()),
                ('examples', models.JSONField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
