# Generated by Django 5.2.1 on 2025-06-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_journalentry_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='daily_streak',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='phrases_learned',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='conversations_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='journals_written',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='phrases_practiced',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='words_learned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
