# Generated by Django 5.2.1 on 2025-06-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_userprogress_daily_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='seen_phrases',
            field=models.ManyToManyField(blank=True, to='myapp.phrase'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='seen_words',
            field=models.ManyToManyField(blank=True, to='myapp.word'),
        ),
    ]
